# cargo-release configuration
# https://github.com/crate-ci/cargo-release

allow-branch = ["main"]
sign-commit = false
sign-tag = false
publish = false  # GitHub Actionsでcrates.io公開するため

pre-release-commit-message = "chore: release {{version}}"
tag-message = "Release {{version}}"
tag-name = "v{{version}}"

pre-release-replacements = [
  { file = "CHANGELOG.md", search = "\\[Unreleased\\]", replace = "[Unreleased]\n\n## [{{version}}] - {{date}}" },
]
